### PR TITLE
fix: left padding on content section

### LINKED ISSUE #774: Spacing too small on the left
Screenshot_from_2020-09-15_11-15-00

Spacing on the left is too small

Firefox on Ubuntu

### PR DESCRIPTION
**Pull request by pgray-hiro**
## Description

Fix content butting up against the scrollbar when the window is collapsed but hasn't yet hit the mobile breakpoint.  This resolves #774.

Screen Shot 2021-05-11 at 5 15 58 PM

## Checklist

- [x] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] New links to files and images were verified
- [x] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [x] Clear code samples were provided
- [x] People were tagged for review

### CODE REVIEW

**Review by agraebe — APPROVED** [review]
LGTM

File: src/components/layouts/base-layout.tsx [hunk 1]
```diff
@@ -36,6 +36,7 @@ const BaseLayout: React.FC<{ isHome?: boolean }> = ({ children }) => {
               <Flex
                 flexDirection={['column', 'column', 'row', 'row']}
                 maxWidth={`${CONTENT_MAX_WIDTH}px`}
+                pl={4}
```
Comment (aulneau) [inline src/components/layouts/base-layout.tsx:39]: we try to avoid using the number values for spacing, see a list of named literals here: https://github.com/blockstack/ui/blob/main/packages/ui-theme/src/literal-types.ts#L13 and values they map to here https://github.com/blockstack/ui/blob/main/packages/ui-theme/src/sizes.ts#L23

```suggestion
                pl="base"
```

**Review by aulneau — APPROVED** [review]
